better naming?

diff --git a/bin/build-web-site b/bin/build-web-site
--- a/bin/build-web-site
+++ b/bin/build-web-site
@@ -17,8 +17,8 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307, USA.
 
-if ! cd $HOME/www.proftpd.org/; then
-	echo "Couldn't change to $HOME/www.proftpd.org/, exiting."
+if ! cd $HOME/www.proftpd.org.git/; then
+	echo "Couldn't change to $HOME/www.proftpd.org.git/, exiting."
 	exit 1
 fi
 
